### DISCUSSION TITLE
믹스인 초안 공유 및 네이밍 추천

### DISCUSSION THREAD

**Discussion by devkyoung2** [KakaoFunding/front-end#24] [General]
여러분들 제가 자주 쓰일법한 믹스인 네개 정도만 추려봤습니다.
각각 주석을 달아두었으니 확인 한 번 해주세요
그리고, 

1. 조금 불편할 수도 있을 것 같은 부분
2. 더 좋은 믹스인네이밍/변수네이밍
3. 이 밖에도 자주 쓰일 만한 믹스인

등등이 있으시면 편하게 말씀해주세요 생각나실때마다 여기에 의견 주시면 감사하겠습니다 !

그리고 tailwind가 이런식으로 축약된 스타일을 태그에 적용하는거로 알고있는데,  tailwind 사용하시면서 편리하셨던 축약형 있으시면   의견 주세요 !

```scss
// 요소 가운데 정렬
@mixin center($direction) {
  display: flex;
  flex-direction: $direction;
  justify-content: center;
  align-items: center;
}

// 요소 전체 너비 높이 적용
@mixin wh-full {
  width: 100%;
  height: 100%;
}

// 요소 사이즈 정의
@mixin size($width, $height, $margin, $padding) {
  width: $width;
  height: $height;
  margin: $margin;
  padding: $padding;
  box-sizing: border-box;
}

// 요소 그림자 적용
// 카카오톡 선물하기 서비스에 그림자가 별로 없긴한데 캐러셀에 화살표에 그림자가 적용되어있더라구요 . . 
// 숫자는 임의로 적용한거입니다!
@mixin shadow {
  box-shadow: 0 2px 4px 2px rgba(0,0,0,.04);
}

```
